### ISSUE TITLE
Offhand grapple

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#107]
We should have `+hook`. Several assets are required: 
- Grapple model
- Rope model
- Grapple fire sound
- Grapple fly sound
- Grapple hit sound
- Grapple retrieve sound

If someone can source these assets, I will begin implementation of the game code and physics for this.

**Comment by jdolan** [comment]
@Cgreenhaw @dmitripot @jar3817 Any interest in helping with the assets for the grapple?

**Comment by jdolan** [comment]
@nilium ^

**Comment by nilium** [comment]
`<jdolan> Nilium: HINT HINT HIIIIIIIIINT`

There anything in particular we're looking for in a rope/grapple model?

**Comment by jdolan** [comment]
@nilium Are you familiar with the Quake2 one from ThreeWave CTF? The rope was just a textured stick. The hook resembled one of those claws you see in the arcade machines where you try to snag a stuffed animal. Something similar would be familiar and totally acceptable.

**Comment by jdolan** [comment]
@nilium Let me ponder the best way to "tile" the rope model and I'll get back to you on that part.

**Comment by maci0** [comment]
so is this like the grapple in zelda games ? where you have certain surfaces you can hook to and get pulled to them or pull them to you?

**Comment by jdolan** [comment]
Uh. I guess. Did you never play QW or Q2 CTF? Jesus, man ;)

**Comment by nilium** [comment]
I DIDN'T PLAY IT. THAT WAS ME.

Did not play QW, did not own Q2 until around 2007 or 2008.

-noel

**Comment by jar3817** [comment]
What did you do from 1997 to 2007?

**Comment by dmitripot** [comment]
Sorry, been kinda buried in stuff this year. As soon as I get back from visiting family in Russia, I'm down to make some assets. Been a while since I did anything real quake-wise.

**Comment by dmitripot** [comment]
This though. 
![w_hook](https://cloud.githubusercontent.com/assets/4108751/11079782/bcd66e42-881f-11e5-954f-17930629a0c0.jpg)

Here I have the TGA of the pic and also the ammo box/pics for prox launcher (another weapon that's good to have for TA-esque gamemodes): http://host-a.net/u/Captain%20Qwerty/prepare-teamplay.zip

Prox reserves the violet-pink color ala Q3TA.

**Comment by jdolan** [comment]
@dmitripot Nice idea for the proximity mines. The impediment here would be the gun model itself, obviously. If that's something you're willing to take on, let's open a new issue and move the discussion there.

@nilium Would you still consider making a grapple model with a "tile-able" rope model?

**Comment by kaadmy** [comment]
This seems a bit dead...
If I make the rope/grapple modes, can @jdolan implement the physics for it?

**Comment by jdolan** [comment]
I'm not even sure exactly what to do for a grapple model. My thinking all along has been to implement the "offhand" grapple from Lithium2 -- that is, the grapple is always ready, and you do not see it as the player's gun model. In this case, there's really nothing to show for it.

However, we *could* attach two models to the weapon tag on the player, if we wanted to. As long as the grapple model was centered to not clip into the weapon, that would work. I don't have a strong preference. We could always forego the grapple weapon model for now, and add it in later.

As far as the physics coding goes, we could easily port this from Quake2 CTF, Lithium2, etc.. You could do it, no problem. Any of us could.

**Comment by nilium** [comment]
Voting for a cannon that fires a skull that chomps down on things to act as a grapple.

**Comment by kaadmy** [comment]
TIL Github has rections.

**Comment by kaadmy** [comment]
I've made a grapple hook model, it's pretty ugly but can work for testing.

Commit: https://github.com/jdolan/quetoo-data/commit/e292a517cff43e555a6ed4ca1b483fb6c38cb627

**Comment by Paril** [comment]
Do we want to go with off-hand hook? If so, do we want a swing hook or a pull hook? I've always been partial to the swing-style hook honestly, skillshots with that hook were always so much cooler than the pull-hook.

We could go with a weapon hook as well, with an additional "+quickhook" command or something that switches to the hook and fires it immediately, keeping you attached until you let go; can reduce the weapon-switch time for weapon->hook and hook->weapon as well, to make it feel a bit smoother. Lots of options, either way I'm ok with it. I love the Q1 hook the best since it was a great weapon too, though :(

**Comment by jdolan** [comment]
Good questions, @Paril. I'd like to have @Panjoo's input on this. Also Pan, I'm not sure if you happened to notice @kaadmy 's grapple hook model (see commit above).

**Comment by Paril** [comment]
Well I mean we can use placeholder models until we're ready, I'm wondering moreso about the mechanics before I start :)

**Comment by jdolan** [comment]
Right, Pan has a say in game design decisions -- I wasn't looping him in [just] for artwork :)

**Comment by Paril** [comment]
Yeah I'm just clarifying in case he thinks we're mostly asking about the models, lol

**Comment by Panjoo** [comment]
I've been rather busy with porting aerowalk but I'll check out the grapplehook as soon as I can.
I've played Q2's LithiumII mod for years which had a pull hook (with default hook_speed 900, hook_pullspeed 700 and sv_airaccelerate 10). The cool thing was you could use the hook to give you a boost and it allowed you to build up insane speeds and also make 90 degree turns at full speed because of the airaccel. 
Also the airaccel gave the player "hangtime", you fired the hook at a high point and the soon as it pulled you up, you unhooked and pressed +back. You could keep yourself bouncing in the air if you were fast enough. Some fuckers always complained about the lack of strafing but that mod was all about hookskill.
Once you learned the hook speedjumping it became a fast game of flying through the maps, clinging to the walls and midair kills. Some servers used a really fast pullspeed and no airaccel, making it possible to strafejump, but impossible to speedjump and steer. Those servers sucked:P
So personally I'd prefer the offhand pullhook over the ctf grapplehook but I like the idea of using a model. Anyway blablabla, I'm fine with both as long as you can fire at the same time and not have to switch to fire weapons.

**Comment by Paril** [comment]
The latest branch has a hook implemented which is functionally the same as the Lithium hook - setting g_enable_hook to 1 will enable it in all gamemodes, +hook is the command. See if it is to your liking. I will add cvars for the speed and pullspeed as well.

**Comment by kaadmy** [comment]
I personally prefer the swing hook, because you can get insane speeds with it :D

**Comment by Paril** [comment]
Same, and the craziness of seeing people swing and get railshots is amazing. I might implement both and just have it a toggle, since it's just different pull physics really.

**Comment by jdolan** [comment]
Nice! Works pretty well so far. Feedback:

 * Player view oscillates when issuing movement commands while hooked. Some check to flat out disable movement while hooked in place (or when move type is PM_HOOK and no ground entity is found) would probably fix this.
 * Cvar should probably be named `g_hook` since we don't use "enable" anywhere else. Most of our cvars enable or disable something -- that's what they're for ;)
 * Cvar is currently `CVAR_LATCH` -- why?
 * Cvar should be voteable!
 * Cvar should be available via worldspawn / maps.list / etc.

This is great! @Panjoo looks like we're gonna need some CTF maps ;)
