### ISSUE TITLE
Windows build fails because of missing MSVSCR110.dll

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#178]
Apparently quetoo.exe requires the MSVCR110.dll shared library. On the Fedora cross-compilation host, there does exist a `libmsvcr110.a` static library. We should either figure out how to statically link the C runtime for MinGW, or we should find and bundle the shared library.

**Comment by jdolan** [comment]
@jar3817 It seems like we're not the only ones to have this one. It's a very widely asked question, with a simple enough answer right from Microsoft. If you feel like this isn't worth fixing, and that folks will have or should just install `msvcr110.dll`, then I am okay with closing this. I defer to your judgement. You're more of a Windows expert than I am.

**Comment by tapir** [comment]
Isn't it legal to distribute `msvcr110.dll` ? I see *a lot* of apps that comes prepackaged with it.

**Comment by jdolan** [comment]
I have no idea if it's legal, or common, etc.. to distribute it.

**Comment by jar3817** [comment]
Legal, schmegal...

**Comment by jdolan** [comment]
@Paril You probably know what the right thing to do here is..

**Comment by Paril** [comment]
This is a tough one that Microsofty folks have been debating for a long time; to statically link or not to statically link. Here's the sitch: for Windows users, this is rarely a problem because nearly all of these runtimes are either distributed with Windows Update, with the installation of Windows itself (usually like the last year's version though) or the redist .exe is linked to or included with the game's binaries. Steam automatically handles this stuff too, so it's extremely rare that Windows users, whether they know what they're doing or not, ever run into a missing runtime.

Statically linking the runtime is handy because you don't have to redist, but it does increase the file size quite heftily. If you can figure out how to do that, that is definitely your best option. If you cannot, however, Microsoft's recommendation is to indeed redistribute the library itself: https://support.microsoft.com/en-us/kb/326922

**Comment by jdolan** [comment]
Okay. MinGW does not provide msvcr*.dll due to copyright reasons. I guess we'll just let users find this on their own, in the somewhat off chance that they don't already have it.

The only reason I could see for us to bundle a particular msvcr110.dll, is if we find that Quetoo only runs with that version. As of right now, I don't think we can make that case.
