### ISSUE TITLE
Menu background

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#191]
As the current menu has no background, I decided to make one.
It's mostly a mockup, I can make changes if it's not high quality enough yet.

https://usercontent.irccloud-cdn.com/file/po96D5Ve/quetoo_menu_bg_2.png

**Edit**: new image

**Comment by Panjoo** [comment]
That's actually not a bad idea. Backgrounds shouldn't be obtrusive so I like that you blurred out the screenshot. I'd probably place the icon on the right side so that it won't look messy in combination with console text. That said, I would definitely prefer to use the Quetoo logo for this because... well that's the name of the game;)  Then you'll get something looking like this maybe:

![feedbackgrnd](https://cloud.githubusercontent.com/assets/10857572/18731063/f88ca054-8059-11e6-9a4b-9cacb097a57e.jpg)

**Comment by kaadmy** [comment]
Ah, I didn't think about the console text getting in the way. I can move the logo to the opposite side.
Also the full logo looks better than the icon IMO.

**Comment by jdolan** [comment]
I scaled the size down to 2560x1440, because it was just taking too long to load (and chewing through 32MB of texture memory). I also altered how the console is drawn when in-game to make good use of this image. Looks nice! Thanks @kaadmy.
