### ISSUE TITLE
A few of the gear faces in lavatomb are lava

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#197]
http://i.imgur.com/fsn2krJ.jpg

A couple of these faces (where I've shot blaster) appear to be lava and hurt you. I was jumping over one and mysteriously died.

**Comment by jdolan** [comment]
Heh. What's actually going on here is that the func_rotating failed to move you out of its way and into a good position, so you got crushed.

**Comment by Paril** [comment]
I thought so, but that is not the case. You take lava damage, not crushing
damage. Those faces are definitely lava :)
Try it yourself. Go to the top of the rotator with the gears and step on
them all individually; most won't hurt you, but some will deal lava damage.
When you die, you "do a backflip into the lava". I literally jumped -over-
the gear (as in, I did a double-jump off of the gear) and got killed by it
because I rubbed against the face.

**Comment by Panjoo** [comment]
> Those faces are definitely lava :)

That's the odd thing, they're not. I know exactly what you're talking about here Paril:). When I made the map this was one of the many strange bugs I encountered. Here is a snippet of one of the emails that I sent right after releasing the first lavatomb version, over 1.5 years ago:
_"-In some areas it looks as if the game thinks the player is inside a liquid volume and you can also hear the underwater sound. When firing a weapon it shows a trail of bubbles (bug1 pic). And shooting the LightningGun at the walls in many places in the map makes a splash sound...  No idea what's going on here. (old screenshot)
![bug1](https://cloud.githubusercontent.com/assets/10857572/18811272/ff5ea03c-82aa-11e6-8a4a-0820855615a7.jpg)
-Spinner: when you try to stay on the gear wheel teeth you sometimes will get hurt as if by lava. Also if you try to wedge yourself in between the teeth it can crush you, even if you're not touching anything else."_

Just now, -as I did back then- I doublechecked each and every single one of the faces of the spinner (inside and outside) to see if one of them had been set as lava but all of them are solid brushes, no liquid properties. The compiler also didn't give me any "mixed face contents" warning, so I doubt this can be fixed by me as mapper. I have no coding knowledge but back when I first noticed this bug I was thinking that it might have something to do with the fact that the func_roting is intersecting the lava volume?

**Comment by Paril** [comment]
That's the only thing I can think of as well. The faces that are touching the lava during the build are the ones that are affected.

**Comment by Panjoo** [comment]
OK I think you misundertood me or maybe I wasn't clear about the wedge bug. What I meant was that at the time I was getting crushed while there was no actual collision. 

> "... even if you're not touching anything else."

It could happen while I was just riding the top of the gears and tried squatting between them. That doesn't happen in the Q2 version of the 'roller'. I haven't bothered trying this in a long time so it might have been fixed by now but this was definitely a behaviour that shouldn't be happening.

**Comment by Paril** [comment]
Oh gotcha, thought you meant if you stand in the middle of the two gear teeth.

**Comment by jdolan** [comment]
@Panjoo fixed this one by making the lava a `func_water` that spawns into the pool. This way, the rotator does not clip against `CONTENTS_LAVA` during BSP compilation, and the faces are no longer lava.

**Comment by Panjoo** [comment]
@jdolan Ehm... nope, this is not fixed yet.

The func_water is only used for the lava near the stepping stones (at RL cave), to prevent a visible crack in the lava surface.

I did actually test the rotator with a func_water in place but it still acted the same as before so I changed it back to normal lava. I think the func_rotating entity is just not working as it should since there is nothing else I can try to get rid of these hurting lava faces.
I already rebuild the entire rotator and also put a 12-sided clipbrush closely around the gears so that you couldn't get in between them. Still same result. Also trying different spawnflags like 'stop' when blocked and 'dmg 0' didn't seem to 'take'. Even _completely removing all the lava from the map didn't fix the problem_.

**Comment by Paril** [comment]
That's fucking strange. Can you build a .bsp of the map that has no lava and be 100% certain that NO surfaces in the map have lava on them at all? Such a .bsp would be incredibly helpful for me to debug this problem.

**Comment by Panjoo** [comment]
Sure, will get right on that.

**Comment by Panjoo** [comment]
[nolavatomb-bsp.zip](https://github.com/jdolan/quetoo/files/573496/nolavatomb-bsp.zip)

**Comment by Paril** [comment]
Alright, so I'm still stepping through things figuring out exactly how it's happening, but the rotating spinner has CONTENTS_LAVA on it. The only thing I can think of offhand is that those faces do indeed have CONTENTS_LAVA on them, I don't see how else it could be pulling that bitflag from the air. It happens in Pm_CheckWater -> Cl_PointContents where it gets the 8 bitflag from Cm_TransformedPointContents on entity ##75 (the func_rotating). Leaf ##3949 (leaf brush ##5645, brush ##1947, first_brush_side ##14174) has contents 9 on it, which is SOLID + LAVA. Can you provide the .map that produced that exact .bsp (no changes, otherwise those numbers above may have changed)?

I'm not so sure how else I can proceed from here. -Somehow-, the CONTENTS_LAVA flag is being assigned to those two/three faces on that rotator. Only @jdolan could really figure it out from here I think.. the results of quemap should be deterministic, he should be able to figure out why that brush side is producing those contents.

**Comment by Panjoo** [comment]
These are the textures in the map that contain "lava" in their names:
_brlava_ -> the actual lava texture
_sublava_ -> sidewalls of lava pits
_sublavabotm_ ->bottom of lava pits

However, the func_rotating itself only uses the following textures:
_caulk_
_lead1_2_
_pyramids_

**Comment by Paril** [comment]
.map, not the .bsp. Will need to figure out where in Quemap that CONTENTS_LAVA is being pushed onto the final brush.

I'm wondering if the folder being "lavatomb/" is somehow causing it to do that somehow. It seems unlikely, but that's the -only- place where flag 8 is added to brushes.

**Comment by jdolan** [comment]
It seems like that was the problem, @Paril. I removed the implicit flags for water, lava and slime, recompiled the map, and this problem is now gone.

**Comment by Panjoo** [comment]
[nolavatomb-map.zip](https://github.com/jdolan/quetoo/files/574145/nolavatomb-map.zip)
(in case you still need the map without lava)
