### ISSUE TITLE
Windows updater doesn't update itself

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#204]
The updater will be for ever frozen at the version that  a user downloads.

**Comment by jdolan** [comment]
One option here, I guess, is to rsync the updater and its dependencies individually, specify new target names for them. The process would look like this:

 1 . `_spawnl` rsync as we do currently, with exclusions for quetoo-update.exe, rsync.exe, and cygwin.dll.
 2. `_spawnl` rsync for each of those 3 files, separately, specifying unique local filenames like `quetoo-update.exe.new`, `rsync.exe.new`, ..
 3. Include a `post-update.bat` file that checks for `*.new` and renames them each, stripping the `.new` suffix.
 4. `_spawnl` post-update.bat with the `NOWAIT` flag, so that the updater terminates, while the .bat file runs.

@Paril Does this sound reasonable / sane?

**Comment by jdolan** [comment]
Assigning to @Paril for feedback on the suggested approach.

**Comment by jdolan** [comment]
Done.
