### ISSUE TITLE
cg_add_weather snow is way too demanding on the fps(?)

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#236]
Since I'm in the middle of trying to polish some textures and normals for the map _Fractures_, I couldn't help noticing the big drop in frames when the snow is enabled. This weather snow fx is sometimes costing me 100+ (!) frames per second. It doesn't seem to happen this noticable with rain, just snow. 
Is it normal to lose this many frames? On this low-end pc I can't afford to lose 100/fps and still have a smooth game. Now a steady 60 fps should also be enough but it just feels very choppy with weather on.

![cg_subtract_fps_1](https://cloud.githubusercontent.com/assets/10857572/19092351/86b305ea-8a86-11e6-929d-f0e9497d1bee.jpg)

(On a related note: I have a feeling that many of the fx, including weapons like HB and RL are turning out to be framekillers and use way too many particles or something. Just firing some rockets or a spurt of hyper blasts makes my frames (briefly) drop down by 70-80. Maybe this is normal for this type of fx but I can't imagine having a smooth game like this with a bunch of people blasting around.)

**Comment by Paril** [comment]
Curious if maybe higher FPSes causes these effects (specifically Blaster/RL/GL) to spawn more particles. If they aren't consistent, it might explain quick drops from grenades especially.

Weather definitely needs work, and I think some particle operations need to be moved over to the GPU. We should get a test branch going for GL 3.0 stuff and see if maybe that helps.

**Comment by jdolan** [comment]
Yea, @Panjoo I'm really surprised to see this. I see absolutely no change in framerate with weather on or off, and we've had this particle code for years now. But you're not the only one impacted by this, and we'll be addressing it for 1.0. @Paril is already working on an OpenGL 3.0 branch that might enable us to use "instancing" (GL3 rendering technique) that would greatly improve particle performance.

**Comment by Paril** [comment]
Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril hmm
1:46 PM so while I can't confirm this exactly, I may have indirectly noticed another reason why fractures is slow
1:47 PM it's related to sorting, but basically because different types of particles use different textures it causes there to be an absurd amount of texture switching
1:47 PM sitting alone in one spot, 65 diffuse textures
1:47 PM if I fire a rocket out into space, it gets up to about 2000 diffuse texture switches
1:47 PM which also means it's drawing them in smaller clusters
1:48 PM because you combine and draw them as the textures switch
1:48 PM J<•jdolan> Jay Dolan sorry my connection dropped for some of that.
1:48 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril https://www.irccloud.com/pastebin/2EvNaU7a/
 Plain Text • 7 lines raw | line numbers 


1
2
3
4
5
6
7
hmm
1:46 PM so while I can't confirm this exactly, I may have indirectly noticed another reason why fractures is slow
1:47 PM it's related to sorting, but basically because different types of particles use different textures it causes there to be an absurd amount of 
    texture switching
1:47 PM sitting alone in one spot, 65 diffuse textures
1:47 PM if I fire a rocket out into space, it gets up to about 2000 diffuse texture switches
1:47 PM which also means it's drawing them in smaller clusters
1:48 PM because you combine and draw them as the textures switch
1:48 PM J<•jdolan> Jay Dolan i caught "which also means.." on ward.
1:48 PM P<packetflinger> Page Title: Pastebin | IRCCloud
1:48 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril it might be beneficial for particle textures to be mapped to an atlas
1:49 PM J<•jdolan> Jay Dolan yes that's entirely true.
1:49 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril and hand-make the mipmaps if possible
1:49 PM so that we can avoid mipmap leakage
1:49 PM J<•jdolan> Jay Dolan sounds extreme for our needs honestly.
1:49 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril I dunno, particle atlasses are pretty common
1:50 PM J<•jdolan> Jay Dolan hand making mips i mean.
1:50 PM <•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril oh, nah that's simple
1:50 PM by hand-make I mean it can be programmatically generated
1:50 PM it's just that you're mipping it box by box instead of downsizing the whole image, that way you don't leak pixels from other blocks into neighboring blocks
1:50 PM J<•jdolan> Jay Dolan here's another idea..
1:51 PM modify the sort to rank all particles as "same" against each other.
1:51 PM they only need to be sorted against translucent brushes, really.
1:51 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril sort by texture basically?
1:51 PM J<•jdolan> Jay Dolan not each other.
1:51 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril ohhh
1:51 PM gotcha
1:51 PM J<•jdolan> Jay Dolan yes.
1:51 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril yeah that's a good idea
1:51 PM J<•jdolan> Jay Dolan in fact, we could even optimize the sort such that for frames with zero translucent brushes, fuckin skip it.
1:51 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril anyways it's just something I noticed while mucking around
1:52 PM yeah you can, lol
1:52 PM J<•jdolan> Jay Dolan yea that's a good observation.
1:52 PM P<•Paril> Paaaaaaaaaaaaaaaaaaaaaaaaaril you could possibly even skip it if there -are- translucent brushes but no particle is behind any of them
1:52 PM not sure how you'd calculate that though
1:53 PM I won't break my current work to go do that though, but it's an idea that I think will help immensely on fractures
1:53 PM J<•jdolan> Jay Dolan i'll paste this convo into the ticket.
1:54 PM actually, since half of my buffer is gone, do you mind pasting this into that ticket?

**Comment by Paril** [comment]
Here's a patch that basically does this:

`diff --git a/src/client/cl_screen.c b/src/client/cl_screen.c
index 100692c..f51de44 100644
--- a/src/client/cl_screen.c
+++ b/src/client/cl_screen.c
@@ -179,6 +179,9 @@ static void Cl_DrawRendererStats(void) {
 	y += ch;
 
 	R_DrawString(0, y, va("%d particles", r_view.num_particles), CON_COLOR_WHITE);
+	y += ch;
+
+	R_DrawString(0, y, va("%d alpha surfs", r_view.num_alpha_surfs), CON_COLOR_WHITE);
 
 	R_BindFont(NULL, NULL, NULL);
 }
diff --git a/src/client/cl_view.c b/src/client/cl_view.c
index f66eab1..bf4a563 100644
--- a/src/client/cl_view.c
+++ b/src/client/cl_view.c
@@ -28,7 +28,7 @@ static void Cl_ClearView(void) {
 
 	// reset entity, light, particle and corona counts
 	r_view.num_entities = r_view.num_lights = 0;
-	r_view.num_particles = r_view.num_coronas = 0;
+	r_view.num_particles = r_view.num_coronas = r_view.num_alpha_surfs = 0;
 
 	// reset counters
 	r_view.num_bind_texture = r_view.num_bind_lightmap = r_view.num_bind_deluxemap = 0;
diff --git a/src/client/renderer/r_element.c b/src/client/renderer/r_element.c
index 01b5745..7d2c979 100644
--- a/src/client/renderer/r_element.c
+++ b/src/client/renderer/r_element.c
@@ -78,6 +78,7 @@ static void R_AddBspSurfaceElements(void) {
 				e.origin = (const vec_t *) s->center;
 
 				R_AddElement(&e);
+				r_view.num_alpha_surfs++;
 			}
 		}
 	}
@@ -120,7 +121,8 @@ void R_SortElements(void *data __attribute__((unused))) {
 	if (!r_element_state.count)
 		return;
 
-	R_SortElements_(r_element_state.elements, r_element_state.count);
+	if (r_view.num_alpha_surfs)
+		R_SortElements_(r_element_state.elements, r_element_state.count);
 
 	R_UpdateParticles(r_element_state.elements, r_element_state.count);
 }
diff --git a/src/client/renderer/r_types.h b/src/client/renderer/r_types.h
index 9c970d1..13e1fec 100644
--- a/src/client/renderer/r_types.h
+++ b/src/client/renderer/r_types.h
@@ -22,7 +22,7 @@
 #ifndef __R_TYPES_H__
 #define __R_TYPES_H__
 
-#define OPENGL_CORE
+//#define OPENGL_CORE
 
 #if !defined(USE_SDL_GL)
 #if !defined(OPENGL_CORE)
@@ -850,6 +850,8 @@ typedef struct {
 	uint16_t num_lights;
 	r_light_t lights[MAX_LIGHTS];
 
+	uint16_t num_alpha_surfs;
+
 	r_sustained_light_t sustained_lights[MAX_LIGHTS];
 
 	thread_t *thread; // client thread which populates view
`

It was made for the gl30 branch but it should be trivial to do it by hand.

**Comment by jdolan** [comment]
I think we can close this now?

**Comment by Paril** [comment]
I believe so, the root issue has been addressed (state switches and adding every particle even if you can't see them). It's still intensive, don't get me wrong (it seems like snow sources across the map are being activated too).. I think there are better ways of handling snow effects, but it works much better now than it did for sure.

**Comment by jdolan** [comment]
👍 Thanks for your work on this.
