### ISSUE TITLE
Breakpointing eventually causes something of an infinite loop trying to catch up the game

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#254]
Seems that Sv_Frame has an issue where it just keeps "queueing up" game frames. Once you continue, the game tries to run all of that time you missed (for me it was up to 26k before I gave up).

**Comment by jdolan** [comment]
Hah! What, is that bad or something? ;)

**Comment by jdolan** [comment]
So.. the challenge here is that the server must now (or at least should) loop in `Sv_Frame` if `msec >= QUETOO_TICK_MILLIS * 2`. We never worried about this before, because the server only ran at 30hz. However, with the server running at 60hz, if the client's framerate every dips below 60, suddenly the server effectively drops frames, and the game simulation visibly slows down.

Try it: comment out the for-loop in `Sv_Frame`, and set `cl_max_fps 30`. It's literally the same thing as setting `time_scale 0.5`. So, in order to keep the server running in realtime, I introduced that loop. Given all this, I'm not sure exactly what the right fix is here.

**Comment by Paril** [comment]
In original Q2, the game just didn't try to catch up if the game got too far behind (I think by several seconds). I remember seeing a block of code related to this in EGL as well, which was pretty much exclusively for breakpoints since you can sometimes spend like 20+ minutes breaking through the code somewhere.

**Comment by jdolan** [comment]
Okay, the number of frames we will run to "catch up" is now `QUETOO_TICK_RATE`, or 60 -- in other words, we only ever try to recover 1 second of simulation.
