### ISSUE TITLE
IRC integration

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#266]
What are your thoughts about having IRC integration in the server(and maybe client)?
Then people in IRC can see players joining/leaving ingame servers, etc.

**Comment by jdolan** [comment]
If you'd like to research IRC client libraries and post your findings here, we can determine feasibility and level of effort.

**Comment by Paril** [comment]
IRC is extremely simple. I remember implementing IRC in Quake 2 a long time ago, the library that I used was simple but like 400 lines long, it's insane.

**Comment by jdolan** [comment]
http://www.ulduzsoft.com/libircclient/

It's asynchronous and event-based, which is great because the Quetoo server is single-threaded.

I think I'd want to use this, and relegate it into `sv_irc.c`.

The server should announce its startup, shutdown and client connection events to a configurable IRC server.

 * sv_irc - enable / disable all IRC functionality
 * sv_irc_server - default irc.freenode.net:6667
 * sv_irc_channel - default #quetoo
 * sv_irc_allow_game - enable / disable game module from using IRC

We could even then include a game API entrypoint for allowing the game to send messages to IRC as well. Could be nice for match end, level end, CTF captures, etc..

**Comment by kaadmy** [comment]
I think we could close this now since it's very unlikely we'll use/need it.

**Comment by kaadmy** [comment]
Maybe we could use similar functionality to have a global stats server for the server to report to?

**Comment by jdolan** [comment]
@Paril has actually started on some Discord integration (see #513 ) that would be more desirable anyway. Closing this out.
