### ISSUE TITLE
Shadows should be sorted by their darkness

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#285]
I'd do this myself if I understood the shadow code, but basically the lighter shadows can sometimes (almost all the time) be "over top" of the darker shadows: http://i.imgur.com/QRvJ4vi.jpg the armor here is much lighter yet gets put over top of the player model. This also happens for shadows on the same object - player models do this a lot where a head or legs can render over top of a much darker shadow that was previously rendered.

Sort by overall darkness of the shadow, maybe?

**Comment by jdolan** [comment]
Yea, ..shadows for the same object are already sorted by intensity (or the amount of light that would have hit the surface if not for the shadow):

https://github.com/jdolan/quetoo/blob/master/src/client/renderer/r_lighting.c#L449

Globally sorting all shadows _should_ be possible, tho they are not currently pushed into any sort of collection to allow that. But I guess first, I'd need to understand why the current attempt at sorting fails. It could be the attenuation code.. like maybe the shadow occludes the most light at the point where it was cast, but it attenuates more quickly than the others for some reason, so when its rendered, it looks lighter than the others. I'm not sure. Disabling the attenuation in the shader would probably be the first step in understanding this.

**Comment by jdolan** [comment]
You know what I think we're seeing here? Linked entities (torso, head, weapon) share their `r_lighting_t` with their parent. This is so that `cl_entity_t::lighting` can be cached over multiple frames, and only recalculated when its considered dirty.

Then, in the shader, we calculate per-pixel shadow attenuation for each mesh. So the head or weapon is drawn with the attenuation for where it actually sits, but using the shadow intensity of the legs. This would definitely yield situations where the torso, head and weapon shadows appear "lighter" than the legs, and are unfortunately drawn afterwards.

I'm afraid there's not an easy fix here. Either we stop caching `r_lighting_t` on `cl_entity_t`, and we calculate it every frame for every entity, or we default `r_shadows` to `2` for 1.0 if we agree that this looks bad enough to warrant disabling it. The problem is far less visible with `r_shadows 2`.

**Comment by Paril** [comment]
Gotcha.

Honestly there's a more pressing bug where the offsets of the head/legs/weapon are all messed up when you change weapons. Look down on r_shadows 3 and switch weapons, things go kinda nuts.

**Comment by Paril** [comment]
I wonder, what if we just have an extra bit in the shadow shader that checks if the fragment will be lighter or darker after applying the shadow, and not applying it if it'll make it lighter?

**Comment by jdolan** [comment]
That sounds perfect! I wish it could just be done with a smarter stencil function, but we're using the stencil value to identify the shadow plane, so writing the shadow intensity into the stencil buffer wouldn't work.

But inspecting the fragment color in the shader (or really, just using `min(shadowColor, fragColor)` should totally do the trick. Great idea.

**Comment by Paril** [comment]
I just realized that we can't access the current screen fragment color from the shader, nevermind :( the only way we could do that is if we used an FBO for regular rendering and passed that FBO texture as input I think

**Comment by jdolan** [comment]
I was curious about that.. Ah well. So your partial fix is about as good as we can do for now. The question, then, is: do we default r_shadows to 2 instead of 3 for the general release?

**Comment by Paril** [comment]
r_shadows should default to 2, but the option should be in SYSTEM to enable "Highest" shadows for 3.
