### ISSUE TITLE
BFG breaks damageable buttons

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#287]
Some oddities I ran into with Gym: only one door had the regular health, the others required like 20 rail shots to go down.

BFG spawns lasers pointing towards origin.

**Comment by Panjoo** [comment]
I knew about the BFG messing up the targets and the lasers pointing towards origin like you said.
After you fire a BFG the targets don't work anymore or can take a lot of damage suddenly. But since you won't be having a BFG in this map I thought forget it. 

You say doors but actually the targets are `func_buttons` with 'health 100' and they all work fine as far as I can tell. It's only after doing a "give all" and using BFG that something goes wrong. 
I'm planning on tuning the fog with the extra opacity feature anyway so let me know if it turns out to be something with the entities.

**Comment by Paril** [comment]
I'm not sure how it happened, I can't repro it any more. It took like 8 rail shots for the button to get triggered every time. I need to poke around the code, I might have broken something.
