### ISSUE TITLE
Light flares shine through entity models.

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#300]
see title ^

![flarebug0](https://cloud.githubusercontent.com/assets/10857572/21467958/9dfb2b70-c9ff-11e6-8c82-f179d02fc52a.jpg)

![flarebug1](https://cloud.githubusercontent.com/assets/10857572/21467959/a0cf566e-c9ff-11e6-81d9-8268aad9e772.jpg)

**Comment by Paril** [comment]
I could have it trace through entity boxes but it would still kinda not work properly (weapon-in-hand models wouldn't show them properly and flares wouldn't shine from behind entities).. flares ignore depth when they get rendered so that they shine nicely around corners, but maybe having them always be visible isn't the best option.

**Comment by jdolan** [comment]
So.. short answer: can't cleanly and easily be fixed.

Long answer:

As far as players and giblets go, it's actually only *your* player model that will not occlude flares. All other players, and all giblets, will occlude flares. Your own player entity is skipped from all collision testing on the client side, which is why flares shine through your player. Practically speaking, the only time users might see this is when using the chase camera.

As far as pickup items go, they are not solids, as far as the client is concerned. Changing that is not impossible, but I'm not willing to risk major prediction regressions to fix what I would consider a very minor bug. We can save this one for a rainy day.

**Comment by Panjoo** [comment]
I see, well that makes sense so it's not a problem then. Also, it sometimes seems to add a nice subtle glow "around" items so it's a nice side effect I guess;)
