### ISSUE TITLE
Remove reference counting from materials subsystem

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#305]
The materials system uses reference counting to attempt to share materials across subsystems (renderer and collision). Unfortunately, this makes materials a bit treacherous to work with (see #304 as well as previous quemap crashes).

It'd probably be better if materials just used an array and a count, like everything else:

```
typedef struct {
// ...
    cm_material_t *materials;
    uint16_t num_materials;
// ...
} cm_bsp_t;

// ...

typedef struct {
    // ...
    r_material_t *materials
    uint16_t num_materials;
    // ...
} r_model_t;
```

The collision system should still handle parsing them into memory, but should expose a function for this purpose, e.g.:

```
size_t Cm_LoadMaterials(const char *path, cm_material_t **out);
```

Collision can call this and simply hold onto them; renderer could call this, iterate and extend them into `r_material_t`, and then free them.

I think this will avoid more pitfalls (current ones hiding, plus future bugs), and allow us to remove quite a bit of glib-heavy code.

**Comment by Paril** [comment]
So, I'm still not sure about this one entirely since we did discuss this further in depth on IRC. Basically here's what we figured out:

- Less memory usage/no duplicate materials regardless of where they came from
- Ability to change a material and have it affect every place where it's been loaded easily
- Lookup table comes with the system, which is important because materials may reference each other

If we dropped the ref system, we'd also have to implement lookup tables in other systems that want to use materials (renderer already has one in the form of media), and refreshing materials on the fly would be nigh impossible unless they all had the ability to reload them and they were all called separately, although that seems dumb as shit.

I made the "initialize state" nicer in ac20860 so that you no longer have to call Cm_Init (it's a blank function right now) and materials will just work regardless of the load state. You will still have to call Cm_Shutdown to free all materials in the odd case where you wanted to reload the state of cm (which is never, currently, since Cm shutdown = program exit).

One thing we could think about doing is is indeed doing the size_t/cm_material_t **out bit that was suggested above. I like using GArray because it does the auto-expand and whatnot, but we certainly can just copy out the result and not have to pass a GArray around if you feel that that is nicer.

**Comment by jdolan** [comment]
I'm not sure other systems require a lookup table. For the server and quemap, materials are loaded at startup, and are simply a pointer on texinfo. When loading texinfo, we iterate the loaded materials to find the material of the same name. It's very simple.

Another issue I ran into with this is that materials are not reloaded during `r_restart`. This means, to see materials changes take place, you have to load another map and then go back to the map you were tuning materials for. Obviously, the in-game editor will minimize this use case, but it still feels really wrong to have materials not refreshed on r_restart.

I'm still of the opinion that the current system's complexity outweighs its benefits, and it's also different from everything else in the game.

**Comment by jdolan** [comment]
Does your work on the BSP representations issue give you new insight as to how to solve this one without the reference counting?

**Comment by Paril** [comment]
Materials aren't reloaded on r_restart right now because of the ref counting, but ideally we'd still need a separate command to reload them anyways since there may be flags in the material that will affect the cm system (for instance, footstep sounds - these are stored in the cm_material_t and would affect the game/cgame, so cm_material_ts would need to be reloaded as well). Having them split would fix the renderer bit, but the server will still need a special way to reload its materials. This one is tough because pointers could be stored in many places to cm_material_ts, although currently only texinfo stores one. To be completely honest, I'm not sure how we could re-load them all in place + take care of new materials + remove old materials, whether we keep the ref counting or not; needs more thought.

By "lookup table" I mean any sort of system that would have it find the material that is already loaded in memory, which includes a naive loop to find matching names. The cm_material system handles this already, which is why I'm saying it's just added code to do this 3 separate ways when it's just got 1 way right now.

No other system needs to sync up the same data pointers between server/client and renderer, so of course it's not the same as anything we already have. The only other system that sort of does this is BSP, and if you try to modify the .bsp file and then r_restart you will get either a crash or a version mismatch (have not tested so not 100% sure what the results will be) because the cm_bsp_t structure does not get reloaded as the server itself does not reload. This is the same issue, just that I ensure that the in-memory representations match on an r_restart so that that couldn't cause an issue for materials. The only thing missing is to figure out a way to gracefully reload materials across both the cm_ and r_ structures.

I guess the main thing is that while there is a bit of added complexity in the reference counting, if we pulled the reference counting the complexity is just going to get offset to the code added to the other areas to add the stuff that ends up being missing from here. The big problem of reloading is still at the forefront.

There's probably a way to do this without reference counting while solving all the other problems too, but it's just not obviously clear to me. I'll poke around the usage and see what I can see.
