### ISSUE TITLE
Machinegun fires way too fast, causes issues.

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#336]
The MG's fire rate being every frame causes a few problems - if you're being shot every single frame, you slide across the ground because of the kickback and it makes it extremely difficult/impossible to move out of the way. It's easier to see if you're fighting bots, but hopefully we can figure out how to stop this.. maybe remove knockback on MG?

**Comment by jdolan** [comment]
It doesn't fire every frame. It fires every other frame (50ms interval).

**Comment by Paril** [comment]
Right, but whatever the case it's causing problems. If you get somebody in a corner they literally can't escape - no jumping, no moving, anything.

**Comment by jdolan** [comment]
I'd say we reduce knockback and try it. Btw pls don't assign stuff to me. I'm trapped on updater and netcode bugs that nobody else wants :D

**Comment by jdolan** [comment]
@kaadmy This would be a good one for you to play with. We need to tune the MG so that it's effective enough, fires approximately like an MG would fire, kicks like an MG, delivers the right knockback, etc.

Bots are extremely accurate, so testing against bots has its pluses and minuses. But I would certainly use them to assess any changes you make.

**Comment by kaadmy** [comment]
I'll just try to balance whatever I feel like, IMO SG fire rate should be reduced, MG fire rate reduced, and reduced kickback on almost everything.

**Comment by jdolan** [comment]
@kaadmy Let's not just tune all of the weapons willy-nilly. There has to be rhyme and reason to this. I would highly suggest we start here:

http://quake.wikia.com/wiki/Weapons_(Q1)

There are similar pages / tables for each game, so we can use the Q2 reference for some, and Q3 or QL for others. We should aim to be somewhere in the middle of these for **most things**.

@Panjoo this honestly falls under your realm (game design), so I'm totally fine implementing what you think is right. If MG or LG should not have knockback, or should only have very little, then so be it.

For my part, I would like for us to incorporate some of QuakeWorld's knockback, as it opens up the door to really entertaining combination shots where you keep your opponent airborne. There's a touch of this in our RL (upward knockback), and I hope it doesn't go away.

Other than that, I really defer to Pan. @Panjoo if you'd like to make a Google spreadsheet or something with desired firing rates, damage and knockback, I think that'd go a long way towards resolving our gameplay balance / weapon feel issues.

**Comment by kaadmy** [comment]
[Here's](https://docs.google.com/spreadsheets/d/1h6rxyi0ybsz-ETrkZBNLVJYwoaNH1wj4VupDFpq60k8/edit?usp=sharing) a Google Sheet with current/new weapon balances.

**Comment by jdolan** [comment]
Nice, thanks for getting this started @kaadmy. I've updated the sheet with some additional columns to reflect maximum damage per shot and per second. This should give some insight into any imbalance.

**Comment by Panjoo** [comment]
> **jdolan**: For my part, I would like for us to incorporate some of QuakeWorld's knockback, as it opens up the door to really entertaining combination shots where you keep your opponent airborne. There's a touch of this in our RL (upward knockback), and I hope it doesn't go away.

Agreed on the RL:). Knocking someone around with well placed rockets is more unpredictable and has a risk of self damage (=both are good). But a considerable knockback on weapons like MG, SG and LG due to higher firing rate isn't something I would advice. Unlike projectile weapons and the slow RG, the outcome of pinning someone against a wall by keeping your crosshair on him is more predictable. Death of the player that's restricted in his movement. 
Entertaining or not I can easily imagine that being the one who's kept airborne by someone who outplays you gets on your nerves fast and could turn a potential player off. Especially if you can't do much to get out of the ropes, so to speak. If there's anything that can really irritate a person it is continuous poking and pushing! Anyhow, I would think if you want a game that's different then be the first to have less knockback on a weapon like the LG for example. As a finishing off weapon, Q2's equivalent for the LG has always been the Chaingun, and although it doesn't have knockback it's deadly and effective enough.

Thanks for that spreadsheet setup but there isn't much I can do with it now as I honestly don't know how and where to start with tweaking something like this. I'm in the middle of porting another map and optimizing that heavy ass Gehenna map.
That link to quake.wikia.com doesn't say anything about knockback numbers and since coding is not my field I have no idea how to get ahold of Q2's or Q3's exact weapon specifics to compare.
I see mentioning of bots and I saw some commits related to bots but I haven't been able to get a bot game going yet (didn't find any doumentation or cvar so plz enlighten me:) 
Running multiple instances of quetoo has never worked for me here on my mingw32 game so botgames would help and will hopefully be playable.

**Comment by kaadmy** [comment]
Bot control uses/will use `ai_` prefixes, to add/remove bots use `g_ai_add` and `g_ai_remove`, respectively.

I don't remember Q2/Q3 having knockback on anything other than RL/GL, but I might be wrong.

**Comment by jdolan** [comment]
Q2 and Q3 absolutely had knockback for most or all weapons. You never got sent flying backwards from a point-blank super shotgun blast? :)

@Paril has been building out our fledgeling AI lib recently, and there are now very naive bots that you can spar with. As @kaadmy alluded to:

sv_max_clients 8
map edge
g_ai_add 7

You can spectate and chasecam them for your own entertainment.

As for tuning the ballistics, I certainly didn't mean for you to roll up your sleeves and tweak the code :) But if you wanted to highlight or comment on cells in that spreadsheet, or make a copy of that sheet and edit the figures to your liking, then either myself or @kaadmy could take a shot at implementing your changes.

**Comment by Paril** [comment]
Everything in Q2 had knockback, yeah. The issue that we have currently with MG knockback is that PMF_TIME_PUSHED is set, which causes every single Pmove CheckGround to return false even if the knockback didn't send you anywhere - *and* this flag stays for 120 ms, which is insane. This is why I thought MG fired every frame, you were forced to not be able to check for ground for a full 120 ms after each shot hit you, so you just slide across the ground like a greased banana on wheels.

**Comment by Paril** [comment]
Closed because the main issue was the MG kickback and I solved that - we can discuss shotty in another issue :)
