### ISSUE TITLE
View kicks still lock wrong

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#410]
Taking blast damage before going through a teleporter can leave your view kicked.

![quetoo075](https://cloud.githubusercontent.com/assets/567688/22851966/3049f3c0-efef-11e6-8e19-f9311398fd57.png)

**Comment by jdolan** [comment]
@WickedShell care to take a stab at this?

**Comment by jdolan** [comment]
So this is happening when you received `delta_angles` with an active kick. Once the `delta_angles` are added to the view, the kick fails to decay properly.

Kick only applies to pitch and roll, and delta_angles apply to pitch and yaw. So my hunch here is that the delta pitch conflates what the kick decay is trying to do.

Kick angles are *not* client-side only. They are included in the client's movement command, so that if you're taking a kick, it actually impairs your aim -- that's the whole idea. So what happens when you enter a teleporter / respawn with an active kick, is that the server calculates `delta_angles` based off your kicked view.

So the `delta_angles` effectively zero out the kick instantly, but the client keeps decaying the kick for a few milliseconds post-teleporter / respawn. The result is the view gets tilted *opposite* the old kick.

The fix here could be:

 1. `memset` kick when taking delta angles. Easy, works, but is lame. It'd be nice if the kick persisted through teleporters (but not through respawning or chase camera target changes).
 2. When taking delta angles, but *not* respawning, re-kick the view (instantly) to the remaining fraction of un-decayed kick.

Option 2 is way cooler, but also harder.

**Comment by jdolan** [comment]
This is fixed (mostly). I did not add special log for respawn / change chase target / etc. But your view should still return to normal after a kick, even if you take delta angles during the kick.
