### ISSUE TITLE
View kick when respawned

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#429]
Sometimes when you die, the view angle stays the same as normal, but upon respawning, the view kicks to the dead view angle.
I can't reliably reproduce this, but it does happen quite often (1 in 3 deaths or so in instagib for me)

**Comment by jdolan** [comment]
Okay. The "death roll" is now managed as a special view kick. That way it takes place over several frames, instead of snapping your view to the rolled orientation in a single 25ms server tick.

The client has logic that says "If we're dead, don't recoil from this kick." On respawn, the server should send delta angles to reorient your view to the correct position.

I can imagine a scenario where network jitter might cause some sort of race condition here. Did this happen to you locally, or only when playing online? If it's the latter, we might be able to reproduce with `net_loop_latency` and `net_loop_jitter` (e.g. `100` and `20` respectively, or something).

**Comment by kaadmy** [comment]
Happened online on the US East server with 100 ping, I also was getting occasional lag spikes, so jitter might have caused it.

**Comment by jdolan** [comment]
Okay, I was able to reproduce this a couple of times locally, but I had to go rather extreme:

    net_loop_latency 250
    net_loop_jitter 50

What I saw was that you would die, and the view would kick as you'd expect. But, upon respawning, it would re-kick in the opposite direction, leaving you with 60º roll while alive.

**Comment by jdolan** [comment]
Fairly confident this is fixed. Please reopen if you're able to reproduce.
