### ISSUE TITLE
railgun recharge time too slow

### ISSUE THREAD

**Issue by Dracant** [jdolan/quetoo#431]
Paril confirmed railgun time was .4 seconds slower than q2.

Can definitely feel it in instagib.

**Comment by jdolan** [comment]
Hm. Folks have also complained that rail is overpowered. Maybe some middle ground here would be 200ms slower than Quake2?

Here's a google sheet that lays out how much damage per second each weapon is capable of delivering:

https://docs.google.com/spreadsheets/d/1h6rxyi0ybsz-ETrkZBNLVJYwoaNH1wj4VupDFpq60k8/edit#gid=1404809358

I would agree that the rail seems underpowered mathematically. Let's discuss the right balance..

**Comment by Dracant** [comment]
If anything, do what quake live did and reduce the damage done per rail. Don't mess with recycle time. 

Just my humble opinion.

**Comment by Panjoo** [comment]
What? I thought we had long decided to keep rail exactly the same as q2 rail. I felt the slower recharge time as well, and more often than not I couldn't get that last all-or-nothing shot in before dying. Thought it was lag or something. I feel a bit of a rant coming up:P

I'd have a problem with having a modified railgun. Quetoo has already been made less raw than Q2, mostly for the better and sometimes not. Faster weapon switching, faster rockets, better tick rate, easier trickjumping, hyperclimbing to get up just about anywhere to steal items without effort or damage.

Not everything has to be made more (noob)user friendly and that 100% rail should stay because it adds something; the danger of dying in one hit without armor (gives shards and small healths much more value), the satisfation of a dead on hit, the frustration of your targets. And the fact that Q3, Q4 and QL all have a weakened railgun. 
Most of us here (hopefully...) have lots of online playing experience when it comes to this railgun. And I admit, it's always been a love/hate thing but in an interesting way. Nobody hates the 100% damage when they're doing the killing. But they do tend to piss and moan when they're getting gayed over and over by it. 
I really think that you could compare this to video games that let you decide if you're going to be a dick or not. You start slaying civillians for no reason and you'll get in trouble. But they don't make that decision for you by making them immune to your weapons. The same thing could be said about spawnkilling or teamkilling. It could be called the Asshole factor. Of course you can completely disable friendly fire but having that risk of some asshole on your team "accidentally" shooting at you does add some tension. 

Let's not mess with one of the few things that makes _Quetoo_ slightly more "_Q 2_" than the rest are we? To get steam greenlight or to accomodate the few interested people that aren't really Quake-style game fans in the first place? Come on. They're not the ones that are gonna stick around playing this.

Having an approach like Q3 has, ie. spawn with more than 100 health and bleed down sounds like a better plan to me.  It will give some spawn protection and you can still make 1 hit kills on armorless players. And maybe it can be made so that only bots have weaker RG shots.

**Comment by Dracant** [comment]
While I didn't plan on trying to explain my preference, for what it is worth, I 100% agree with Panjoo. 

:)

**Comment by jdolan** [comment]
Railgun firing rate increased, 5 seconds (+5) of health boost on respawn / give all added.

**Comment by Dracant** [comment]
you da man!! :)
