### ISSUE TITLE
Menu improvements

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#457]
The current menu is functional, but not very pretty.
I have a WIP version in the jdolan/menu_cleanup branch, but right now it's not very usable.

- [ ] Sounds, just an idea for now, don't need this
- [x] Set of random menu backgrounds that are chosen on start (5 or so)
- [x] Color theme? I think grays and blue work well alongside Quetoo's logo, but maybe a different color would work better.

Image mockups:
![Mockup keybinding menu](https://cdn.discordapp.com/attachments/224935404506316800/294976090101776384/menu_2.png)
![Mockup video settings menu](https://cdn.discordapp.com/attachments/224935404506316800/294976152861409290/menu_1.png)

Any thoughts on this @jdolan @Paril @Panjoo?

**Comment by jdolan** [comment]
I think there are two distinct issues here:

 1. Rearrange the information architecture of the current menus to match this approach.
 2. Modify the default look and feel of ObjectivelyMVC by implementing subclasses in Quetoo for Button, Select, etc..

I'd recommend tackling them in that order. I think, from an interaction perspective, much of what you're aiming for here can be achieved by rearranging the hierarchy that we have. Some enhancements to MVC might be necessary / wise to provide a `TabView`, `TabViewItem`, and `TabViewController` (see [Cocoa documentation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/TabView/TabView.html#//apple_ref/doc/uid/10000074-BCIEBFAH)).

Then, with the general structure in place, the path to customizing the visual design should be come more clear. That's just my take on how I'd approach this.

**Comment by kaadmy** [comment]
I already have a `TabViewController` for the individual tabs in the settings panel :D
The main menu layout is almost final, still some work needs to be done on the tab layout though.
I haven't gotten to subclassing `Button`, `Select`, `Slider` or anything yet, but it will/should also be done.

**Comment by jdolan** [comment]
This is coming together pretty nicely. Some feedback on the state of your branch as of today:

 1. The top level menus should group [Home] [Profile] [Play] to the left, and the Settings and Quit buttons to the right. Currently, Play is grouped in with Settings and Quit, and they hover in the middle of the screen.
 1. Under Settings, I think the naming should be _Keys_ and _Mouse_, not _Bindings_ and _Input_. Bindings makes sense to us, because we're familiar with the console's innards. Users will understand Keys, and it's shorter and more accurate, too. _Mouse_ makes more sense for the latter, because that's all it currently handles. It's concise, familiar and specific.
 1. We could then merge all of the _Misc_ stuff (which is just crosshair) into _Mouse_, which would fill that panel out nicely.
 1. The tabs in _Settings_ should use the _accessoryView_ for any action buttons ("Apply", ..). Also, I'd suggest that the top-level container (TabViewController) contain "global" actions for "Apply" and "Cancel," rather than wedging the accessory actions into every tab. We can work on "Cancel" later ;)
 1. The _Audio_ tab could be fleshed out with an additional slider for _Ambient sound volume_ and a checkbox for _Own footsteps_ maybe? Both would require simple changes to cgame / engine.
 1. Any reason you lost the border on Boxes?
 1. Some calls to `$(view, sizeToFit)` are missing, or you're perhaps not using `ViewAutoresizeContain` correctly. This is why the _Bindings_ Box blows out the Panel, and why the Panels are not vertically centered.

**Comment by kaadmy** [comment]
1. Since the top bar is currently just a `Panel` with the middle buttons being the accessoryView, I can change this but being in the middle isn't a design decision :D Yesterday I actually tried to group all three main buttons on the left, it looked okay but I reverted it because I was also working on other stuff at the time.

2. Most other games use _Bindings_, since _Keys_ doesn't really fit here because you can also bind to mouse buttons and possibly joystick actions (_hint hint_). Maybe rename it to _Controls_?

3. I named _Misc_ badly and I've been meaning to change it to _Interface_ or something, which could also include other HUD and UI related stuff like blend flash, weapon model toggle, showfps, netgraph, etc.

4. Yeah, I should do that. Before yesterday I was using a `StackView` for the `TabViewController`, but I've since replaced it with a `Panel` which I should actually use correctly now.

5. I haven't touch most of the tabs yet except to clean them up to support other things that are WIP, but in general I'll add a lot more options to everything :)

6. Which boxes, the ones in the _Bindings_ panel? I removed those for simplicity since I think I'll put the binding list into a scrolling box.

7. Hm? Didn't know that, I'll try it.

**Comment by Panjoo** [comment]
At some point I'd like to see a tickbox for stainmaps/decals under System -> Options:

eg. _Permanent decals_ 
Iif enabled: r_stainmap_expire_time 0  / if disabled: r_stainmap_expire_time 15000 (milliseconds)

And maybe also:

_Weather effects_
(cg_add_weather 0/1)

--
Here are other suggestions, although this is probably something for later.
![menu](https://cloud.githubusercontent.com/assets/10857572/24546071/02959e98-160a-11e7-87a4-ca4ec22a3403.jpg)

A while back I suggested the idea to add sounds and so I collected/edited 10 subtle clicksounds for the menu: http://panjoo.tastyspleen.net/quetoo/uploaded/menu-sounds.zip
The placeholder sounds are okay but kind of pinball machine-ish.

**Comment by kaadmy** [comment]
Hm, that tab highlight looks really neat :D

Totally doing that now ;)

Not sure if I'll make each element in the list of binds etc selectable, it
might be a lot of work to do with ObjectivelyMVC.

On Mar 31, 2017 3:05 AM, "Panjoo" <notifications@github.com> wrote:

At some point I'd like to see a tickbox for stainmaps/decals under System
-> Options:

eg. *Permanent decals*
Iif enabled: r_stainmap_expire_time 0 / if disabled: r_stainmap_expire_time
15000 (milliseconds)

And maybe also:

*Weather effects*
(cg_add_weather 0/1)

--
Here are other suggestions, although this is probably something for later.
[image: menu]
<https://cloud.githubusercontent.com/assets/10857572/24546071/02959e98-160a-11e7-87a4-ca4ec22a3403.jpg>

A while back I suggested the idea to add sounds and so I collected/edited
10 subtle clicksounds for the menu: http://panjoo.tastyspleen.net/
quetoo/uploaded/menu-sounds.zip
The placeholder sounds are okay but kind of pinball machine-ish.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/jdolan/quetoo/issues/457#issuecomment-290672825>, or mute
the thread

**Comment by kaadmy** [comment]
Been thinking about the selection thing, I might just add a highlight that shows the last element that was selected, nothing really fancy. Having the source image for the selected tab highlight would be nice too.

**Comment by kaadmy** [comment]
Most of the issues mentioned here are either fixed or replaced by more stable mechanisms. More options have also been added.

![scrot_fullscreen_20170421_203908](https://cloud.githubusercontent.com/assets/14076345/25301079/0597e93c-26d3-11e7-9c79-f9aa727c15f2.png)
![scrot_fullscreen_20170421_204113](https://cloud.githubusercontent.com/assets/14076345/25301080/0598471a-26d3-11e7-9928-4f8dd717fe59.png)
![scrot_fullscreen_20170421_204143](https://cloud.githubusercontent.com/assets/14076345/25301081/059af73a-26d3-11e7-8073-1d83d3b58294.png)

**Comment by kaadmy** [comment]
Also there's now a cgame-side loading screen...

![scrot_fullscreen_20170421_204304](https://cloud.githubusercontent.com/assets/14076345/25301084/2eb70c58-26d3-11e7-96c3-bf934d485db3.png)

It's set up fairly easily to allow for pretty much any customization in the cgame side, allowing for themed loading screens etc.

More loading screen improvement ideas would be helpful, although a low priority as it works already and is usable right now.

**Comment by TenaciousTigerTrumpets** [comment]
Maybe have something animated polling off the main thread so you can tell if the program froze during load. I've seen it happen all too often in other games.

**Comment by jdolan** [comment]
- [ ] [Re-]Add logo to `LoadingViewController`
- [ ] Add bots selection to `CreateServerViewController`
- [ ] Fix alpha blending in `PlayerModelView` (QForcer's visor, among others, do not work unless in-game)
- [ ] Fix initial data binding of `HueColorPicker` and `HsvColorPicker` so that `0` is disabled, not red
- [ ] Fix sorting for servers list, ping and others are not working
- [ ] Fix crash when clicking `InfoViewController` and then anything else
- [ ] Clean up `CreditsViewController`, load JSON, etc. This could be much smaller / simpler with Objectively.

**Comment by kaadmy** [comment]
There already is a logo while loading maps, unless I'm thinking of something else?

I originally didn't add bots since the bot count behaviour is very erratic, depending on when the cvar was set the bot count comes out different.

QForcer's visor seems correct currently, although I have seen it become black before (likely the same issue causing textures to become completely black/corrupted)

I can't cause a crash with the info panel; also it should probably be completely rewritten again since it's pretty hacky already and not yet complete.

The server list sorting is an issue I've already brought up before; the horizontal mouse position is checked as pixels but the column width is defined by a variable width that scales depending on the entire table view, meaning that if you make the view 2x wider, you'll have to click in the horizontal middle to select the far right column.

**Comment by jdolan** [comment]
Thanks for reminding me about the TableView::columnAtPoint bug. That's fixed now.

The logo does not show up in the LoadingVC. The logo is part of the MainVC. In your mockup above, you had a large logo centered in the screen. I think it looks good, but did it obscure too much of the map shot in your opinion?

Maybe @Paril could look at why QForcer's visor and other blend meshes do not render correctly unless in game. Maybe it's a shader state thing or something. To be clear, when in-game and viewing the PlayerSetupVC, the visor looks correct. But it disappears if you launch the PlayerSetupVC without being in-game.

Not sure why the CreditsVC is causing a crash, either. But yes, it should be completely rewritten. Objectively's JSONSerialization would make quick work of parsing a credits.json file with no parsing code or custom model / data struct required.

**Comment by jdolan** [comment]
Another nice touch on the loading screen would be a Label containing the map message, stripped of colors, in the PrimaryResponder font. Maybe that should appear centered in the view, instead of the Quetoo logo..

**Comment by jdolan** [comment]
Hm, yea. I see in the LoadingVC, you have a logo and progressBar, but I never see either in-game. Are the assets just missing? I think I like the idea of the map message instead of the logo, but something's amiss either way. The LoadingVC could probably take advantage of Theme more as well for its loadView implementation.

**Comment by jdolan** [comment]
💥
