### ISSUE TITLE
MinGW 64 bit quetoo.exe crashes on start

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#466]
@Paril has done some investigation into the 64 bit MinGW build, which has odd threading-related crashes (possibly a race condition?) on startup. See #465

**Comment by jdolan** [comment]
If you have time to step through this and figure out what its problem is, that'd be great. Having both builds fully functional would be wonderful for folks with older systems.

**Comment by Paril** [comment]
Some day I'll figure this out. The problem is that it tends to work with debuggers attached, and just randomly decides to not work with no explanation. I really don't know what could do that.

**Comment by jdolan** [comment]
Could someone retest this? I'm using a newer mingw64 on our build slave now. Maybe it's better? :|

**Comment by Panjoo** [comment]
Well, I downloaded this snapshot: http://quetoo.s3.amazonaws.com/snapshots/Quetoo-BETA-i686-w64-mingw32.zip and ran Update.exe
I was hoping to confirm that #489 has been fixed but mingw32 wouldn't start;

![cgame](https://user-images.githubusercontent.com/10857572/36697938-be6f6326-1b48-11e8-840a-e8dd00deace0.jpg)

**Comment by Paril** [comment]
Looks like the cgame DLL is missing from the snapshot.

**Comment by jdolan** [comment]
It looks like there are two problems here:

 * The dynamic class resolution stuff (`dlopen(NULL, 0)`) is failing for the default Stylesheet. Some magic glue like what @Paril did for Windowly is probably required for MinGW, too.
 * For whatever insane reason, the Jenkins build slave refuses to link cgame.dll anymore. I'm trying all sorts of different SDL2 versions, but it keeps complaining about SDL2main.

FML. @Panjoo, I'm just going to throw this out there: Windows 10 is basically free. You can run it without ever activating it. I have an non-activated copy for flight simming. Works great! Just saying :)

**Comment by Panjoo** [comment]
I already knew about that, however when I'm moving over to Win10 or something else, it won't just be for flight simming or quetoo but it'll be my main OS and so I'll need to get all my work-related programs running without problems and figure some stuff out regarding the not-activated thing, as to system updates, restrictions and functionality. Sure, right now there aren't any big issues with a not-activated Win10 but who knows what's going to change next year and what they're gradually going to restrict or shut down.
About three months ago I purchased a new SSHD (hybrid ssd with the larger capacity of hhd) which is going to be my main drive, with Win10 on it, and preferably a dual boot Linux Mint distro. 
I need to install Win10 first before Linux, as Mint will recognize existing Windows installations and install alongside them, and not vice versa. But at the moment I have other things on my mind, and so that new disk is still on my desk waiting for me to finally make the move, lol. But as soon as I feel like it I'll sort it all out and get quetoo up and running.

**Comment by Panjoo** [comment]
Okay got it, but I need to figure some of this stuff out anyway before upgrading.

**Comment by jdolan** [comment]
@Panjoo I was just whining. Really, it's not your problem. I will fix the MinGW build. I want Objectively, MVC and Quetoo to all work under MinGW.

@Paril It _is_ a Win7 problem in that older Win7 systems can't run your [much better] build, so those users are stuck with the old MinGW build. Win7 isn't causing the problem, but it is the only affected platform.

**Comment by kaadmy** [comment]
@jdolan I believe you said you got this fixed already?

**Comment by jdolan** [comment]
I have it _compiling_ locally again. I'll get it going on CI in the next 24 hours or so. I'm also using a newer version of the mingw32-dlfcn polyfill, so it's _possible_ that the dynamic class loading works. But I'll need a Windows user to test that.

**Comment by jdolan** [comment]
Both the 64 bit and 32 bit MinGW builds are compiling again through Jenkins. You should be able to update and snag a new build. *I don't know if the newer mingw32-dlfcn wrapper we're using properly supports `dlopen(NULL, RTLD_GLOBAL)` yet.* So this may start, but bomb trying to get to the user interface. I guess we'll see.

**Comment by Paril** [comment]
Worst case scenario @jdolan we just copy out my Windowly shit into a dlfcn wrapper for both pc-windows and ming.

**Comment by jdolan** [comment]
@Panjoo I would try the 32 bit build first. That's the one that _was_ working fairly recently. The 64 bit MinGW build has never worked (that's what this ticket was originally opened for).

**Comment by jdolan** [comment]
@Paril Word. Or, even better, maybe contribute it to https://github.com/dlfcn-win32/dlfcn-win32

**Comment by jdolan** [comment]
I have no idea if this is still an issue for anyone. @Panjoo are you still using MinGW builds? If so, do they work?

**Comment by Panjoo** [comment]
@jdolan I've been using the Win64 MSVC build for months now. I have no idea if the MinGW builds work on win10 or not, iirc they wouldn't install but I could try again later.

But you might want to edit the text on the Quetoo downloads page where it still says that the MSVC build runs on Windows 7 without SP1, because it doesn't: 

**Windows 10, Windows 8, Windows 7 SP1, Windows 7** <-lies 
The Windows build requires the Microsoft Visual Studio 2017 runtime.

**Windows Vista, Windows XP**
This build is cross-compiled for Windows with MinGW-w64. It uses an older C runtime, and is suitable for older versions of Windows.

**Comment by ypsvlq** [comment]
Currently:
- mingw-w64 can successfully compile all of Quetoo (all I needed was to manually specify CURSES_CFLAGS and CURSES_LIBS to configure).
- The dedicated server works.
- The client segfaults whenever it tries to do formatted output/input (ie printf, scanf, etc).

**Comment by ypsvlq** [comment]
After https://github.com/jdolan/Objectively/commit/24e64cd23d155ff7932319df311ed5006c6f1a9d this should be fixed, just need to check it cross compiles successfully.

**Comment by jdolan** [comment]
Cross compiles! Thank you @ypsvlq. Closing this one out finally :)
