### ISSUE TITLE
Questions about entities, flags, etc.

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#515]
1) I cant get something to work that I thought should be easy.  I need a texture to be visible from both sides and have it collide with projectiles (think of a fence or metal bars.) So one face has the fence texture, the other faces have caulk. 
The only way to make the textured face visible from both sides (no culling) is to set: _mist + alphatest_ (or _blend33/66_)  Then the fence is drawn from both sides but it has no collision because of _mist_.
(I even tried to place invisible brushes as close to the fence as possible that use an empty texture with a black alphachannel, this works but is too much fiddling to get right because the invisible brushes can't touch anything and also add extra polys.)

2) Is it possible to disable or replace the standard sound of a trigger_push? I'd like to use my own sound instead of having it mixed with the standard whoosh sound.

3) Is it possible to change the size of _misc_emit_ flames? Or set things like hz, radius, count? After some experimenting I'm guessing it's not.

4) How do you make lights that flicker like a fire? (In combination with _misc_emit_ flames). Already tried to add misc_emit flashes but I cant get it to flicker fast enough. The light looks nothing like a convincing flame/fire.

**Comment by kaadmy** [comment]
The code currently does not support having custom trigger_push sounds, this seems to be an easy fix though, but I'm not sure how entity fields are compiled/saved.

According to code comments, the `hz` and `radius` fields are parsed and saved, but never used for some reason, should this be fixed @jdolan?

Did you try the `flicker` entity field? It only works with corona emits, but I think that might be a step in the right direction.

**Comment by jdolan** [comment]
Hey @Panjoo , @kaadmy 

1. Regarding the single face brush, I'm not sure why `CONTENTS_MIST` on the brush would be required. By making *all* of the faces of the brush `SURF_ALPHA_TEST` or one of the `SURF_BLEND` flags, that should cause the brush to become `CONTENTS_WINDOW`, which will force back-side faces to not be culled. So I would try that: make all faces on the brush alpha test or blend, and then also make the caulked sides `SURF_SKIP`. See if that helps.

We actually have chain link fences like this on Lilith, especially around the perimeter of the upper level of the map. Did you take a look at how those are done? I'm not entirely sure if they are visible from both sides. If there's a bug here, I'm happy to address it. I might have the time to this weekend.

2. If setting the `noise` or `sound` keys on `trigger_push` does not already work, we can certainly add that. It's an easy enhancement. I would check, but I'm in the midst of installing a 4GB Xcode update right now.

3. Flame emitters are currently not very customizable. You can set the `count` and `hz`, but there's no way to change the _size_ right now, which is an oversight for sure. For larger fires, we currently just place multiple emitters. Let's capture this as a feature enhancement.

4. Add the `light` emit flag to the emitter. Set `radius` to the desired radius in Quake units. Set `color` to a 3-float light color. Set `hz` to how many times you'd like it to flicker per second (default `0.5`), and set `drift` to how much randomization you'd like for the flicker (default `3.0`).

I have not yet tried to tie a separate light emitter to a flame particle emitter. Maybe we should just add a light emission to flame emitters by default, so that every time particles are spawned, the light pulses. That doesn't sound too hard.

**Comment by Panjoo** [comment]
Alright, thanks dudes.

> **jdolan:** We actually have chain link fences like this on Lilith, especially around the perimeter of the upper level of the map. Did you take a look at how those are done?

Did I take a look he asks, hah! Don't you remember how I gave Lilith an extented makeover?:P The fences there aren't vibile from both sides, which wasn't a problem in that map because the player couldn't look behind them anyway.

Making all of the faces of the brush `SURF_ALPHA_TEST` will not look right if you can see the fence from the top or bottom, you'll see a double fence, no matter how thin you try to make the brush (not easy when they're at weird angles). Like I said the backsides get culled if I don't set mist.

`SURF_SKIP` messes everything up (I also have clipbrushes around them) and `SURF_BLEND`'s are just making the whole brush transparent, it doesn't become like a window with visible backside faces. I'm sure it's bugged. Even the windows that I made in Edge are culled, you just don't see it because the sides are covered by solid frame brushes.

> If setting the noise or sound keys on trigger_push does not already work, we can certainly add that.

Nah, it doesn't work. For now I've added another trig_multiple that targets a custom sound but the standard jumppad sound also plays.

> Flame emitters are currently not very customizable. You can set the count and hz, but there's no way to change the size right now

Well at least trying different _count_ and _hz_ lets me add some variety to the flame puffs. This helps somewhat and is probably good enough for the effect I need.

> Add the light emit flag to the emitter. Set radius to the desired radius in Quake units. Set hz to how many times you'd like it to flicker per second, and set drift to how much randomization you'd like for the flicker.

I'm usually very tenacious when it comes to getting map-things to work so I did all this but it refuses to flicker fast enough to mimic the light of a flame. I can see no real difference between hz 3 or 30. I bet this is also bugged or I'm missing something.

**Comment by jdolan** [comment]
> I'm usually very tenacious when it comes to getting map-things to work so I did all this but it refuses to flicker fast enough to mimic the light of a flame. I can see no real difference between hz 3 or 30. I bet this is also bugged or I'm missing something.

Drop `drift` to a very low value (`0.1`). Drift is _added_ to the `hz` interval each time to provide randomization:

    next_fire = (1000 / hz) + (randomf() * drift)

So with a default drift of `3.0` seconds, you're gonna have long intervals.

**Comment by jdolan** [comment]
The busted `CONTENTS_WINDOW` brush stuff, I can look at this weekend. Supposed to be cold outside :)

**Comment by jdolan** [comment]
Adding another one to this: `trigger_hurt` apparently pushes hand grenades straight up, rather than using a plane normal. Hopefully there's an easy fix for this.

**Comment by jdolan** [comment]
`CONTENTS_WINDOW`, `SURF_SKIP`, etc. are all working as expected in `brave-new-world`, and I have a much better understanding of their intended use and implications as well. Happy to revisit this if there are specific questions. Double-sided alpha test faces also work now. So putting `common/skip` on all faces of the brush except a single `SURF_ALPHA_TEST` face will yield exactly what @Panjoo was after here.

The `trigger_hurt` issue should be looked at and addressed in a separate ticket. Closing this out.
