### ISSUE TITLE
Consider data-driven particle system

### ISSUE THREAD

**Issue by SpineyPete** [jdolan/quetoo#559]
Tremulous (ioQ3 based) added .particle files to their engine, which allows emitters to spawn particles, particles can carry their own emitters to chain them together. This allows artists to create complex new particle effects in a syntax very similar to Q3 shader files. We might consider having something like that at some point.

https://github.com/darklegion/tremulous/blob/c862a5340c8de44dcc7abaff170c20c04f9340e8/src/cgame/cg_particles.c

The Tremulous particle system lacks some useful parameters (e.g. you cannot fade in and then out again) and there is no WYSIWYG editor, which makes for cumbersome workflow -- I authored a bunch of them for a mod on several occasions. Some of the nicer bits are the ability to spawn new particles upon impact and have impact sounds.

**Comment by Paril** [comment]
I love particles with WYSIWYG editors. I would like to do this eventually for sure.

**Comment by jdolan** [comment]
So.. we're taking a different direction for _particles_, tho something like this could be done for sprites perhaps? Particles will be simple RGBA points (GL_POINTS), so that we can support tons of them on the screen at once. If you feel that this issue could be retargeted at sprites or misc_emit in general, feel free to adjust and keep open. Otherwise, I'd ask that we close this out.
