### ISSUE TITLE
Migrate flares to client game module

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#603]
Currently, surface flare stages are loaded as part of the renderer loading code, and they are completely internal to the renderer. This is simple, but has limitations. Namely, flares can't "think" and trace to the view origin to ramp their alpha transparency up or down based on occlusion.

It would be nice to instead load flares in the client game module. We should create `cg_flare.{c,h}` and define a client game wrapper `cg_flare_t` just like we have a `cg_sprite_t`. The client game flare instances should be persistent, and should each add an `r_flare_t` instance to the main `r_view_t` struct per frame -- pending a trace result. R_AddFlare will need to be exposed to the client game module.

This will open up the door for mods to customize flares as well, which might be interesting.

**Comment by jdolan** [comment]
@Paril @SpineyPete You might wish to play with the flare attenuation / exposure stuff (like factoring in dot product or something), but this is now done and working.

**Comment by jdolan-chwy** [comment]
Other ideas that might be fun:

1. Merge flares that share a plane and material. Sometimes BSP splits up flare faces, and you end up with two flares next to each other instead of one big flare.
2. Supporting width and height and inferring sprite axis based on the face normal? This might allow us to create those fake light volumes fairly easily. Currently, the flare origin is always the center of the face. That would have to change for this. Or, if this should just be done with misc_sprite, I'm fine with that, too.
