### ISSUE TITLE
See-through sides of some bmodels

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#618]
![](https://i.imgur.com/SmqeJIp.jpg)

This decal also disappears if you're under the water way below. Both issues do not occur with r_depth_pass 0.

**Comment by jdolan-chwy** [comment]
Blended draw elements are drawn after all opaque ones (across all inline models, including world). SURF_DECAL might be disabling depth test, and that would explain what you're seeing here.

**Comment by Paril** [comment]
I'm not sure if this decal in particular is SURF_ALPHA_TEST or not, that's the only one that actually *enables* depthmask during draw elements. Again too this only occurs with depth pass enabled.

**Comment by jdolan** [comment]
It's not `SURF_ALPHA_TEST`. It's `SURF_BLEND_100 | SURF_DECAL`. Decals are excluded from `R_BlendDepthForPoint` but are still back-to-front sorted so that e.g. even decals on glass will work correctly. So the state leak here might have nothing to do with this decal, but it might just be manifesting on it.

**Comment by jdolan** [comment]
Okay, so.. been looking into this. There are a few things going on. I've found and fixed a state leak with materials stages on blended elements (the water on Tokays is blend and also has stages). I've also noticed that this particular inline model has `SURF_ALPHA_TEST` elements: the "holes" where the cable goes through are actually 1u thick "decal" type faces with alpha test. They weren't even showing up in-game. I've fixed that, but they're killing the faces behind them:

![quetoo026](https://user-images.githubusercontent.com/643118/110209774-336ffb80-7e5c-11eb-8415-38ceb0bb5ab2.jpg)

**Comment by jdolan** [comment]
This is all fixed up now. The "cable holes" were killing the faces behind them because the .map had `CONTENTS_SOLID` explicitly set on some of the faces, rather than letting them auto-set to `CONTENTS_WINDOW` by quemap. I'll make sure to re-fix that when I absorb @Panjoo's updated .map files.

![quetoo028](https://user-images.githubusercontent.com/643118/110210220-a5494480-7e5e-11eb-921b-63ac6dd6ffb2.jpg)
