### ISSUE TITLE
Soft particles don't work with bmodels

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#657]
Soft particles require depth buffer information about bmodels, and for some reason inline models aren't rendered before sprites in a way that allows them to have that depth information. Is the depth buffer just out of date? Are sprites actually rendering before the inline model?

![](https://i.imgur.com/krchOIc.png)

**Comment by jdolan** [comment]
I don’t include inline models in the depth pass. It would be fairly easy to do so I suppose. But do we need to even do that? Within each blend depth group, entities as are rendered before sprites. Does the soften routine only use the depth pass buffer, or do things written to the depth buffer after the depth pass also contribute to softening?

**Comment by Panjoo** [comment]
![fps-criminal](https://user-images.githubusercontent.com/10857572/149620914-60bd852f-b6d0-478f-b846-2a7c4fd85524.png)

**Comment by Paril** [comment]
> I don’t include inline models in the depth pass. It would be fairly easy to do so I suppose. But do we need to even do that? Within each blend depth group, entities as are rendered before sprites. Does the soften routine only use the depth pass buffer, or do things written to the depth buffer after the depth pass also contribute to softening?

That might be why, yeah. I didn't consider it was from the depth pass.
I think we did consider adding bmodels to the depth pass before but there may have been a reason why it wasn't easily possible...

**Comment by jdolan** [comment]
The way the scene building works now we might be okay to include them. Depth pass happens after scene is populated (so that it has your view orientation at the very least). I think we have entities in the view. Tho they may not be culled or depth sorted yet. So that would be the rub.

and it’s entirely possible that with my recent “inline models as any other entity” changes, you’ve found a draw order issue where sprites are rendered before that plat…

**Comment by Paril** [comment]
This isn't a new issue, I think it's always been this way. Just haven't reported it till now.

**Comment by Paril** [comment]
Actually, your recent changes may have broken particle rendering over top of bmodels, but I know for sure soft particles only used blend pass so that was always an issue:

![](https://i.imgur.com/QIWULRu.png)

**Comment by Panjoo** [comment]
This is a shot from the Tokay's elevator models, looks like (at least) the softparticles work? I think the difference is that on the Edge elevator bmodel there is a blood decal texture ontop of the plateau.

![softparti-bmodel](https://user-images.githubusercontent.com/10857572/149635076-f5ca9df6-fe13-4dc0-9d87-4565e7278ba1.jpg)

(Btw, off topic perhaps, I noticed that if misc_fog brushes intersect with decal textures it will cut holes in the decal. Had this problem in Fragpipe where fog brushes intersected with the two fanshade decals on the floor. Turned them into func_walls to workaround this.)

**Comment by Paril** [comment]
You might be right, it might only not work on non-opaque bmodels

**Comment by jdolan** [comment]
Fog brushes are written to the BSP because they are not used until the lighting phase of quemap, which does not parse the map, but rather uses the intermediate BSP. Fog brushes eat decals because your decals are CONTENTS_MIST. We conceivably could add a CONTENTS_FOG just after CONTENTS_MIST, and then mist like decals would eat fog. That's probably best...

I'll look at the inline model draw order / soft particle issue now.

**Comment by jdolan** [comment]
This is fixed.
