### ISSUE TITLE
Windows download from Queutoo website is broken

### ISSUE THREAD

**Issue by wtfbbqhax** [jdolan/quetoo#671]
I was curious to see how far this project has come along, and when I navigated to the quetoo website, the Download for windows is broken.

I didn't check any of the other downloads.

--

Another note, is that Firefox will default to trying Secure/HTTPS connections, and is raising a warning on quetoo.org for not supporting https

**Comment by Paril** [comment]
Hey, sorry for the late reply.

Our latest development version can be found here: https://s3.console.aws.amazon.com/s3/object/quetoo?region=us-east-1&prefix=snapshots/Quetoo-BETA-x86_64-develop-pc-windows.zip
Note that it does not include the data; you will have to download a copy of the `quetoo-data` repo (the `develop` branch: https://github.com/jdolan/quetoo-data/) and put `target/default` inside of the `share` folder (so that you have `share/default`).

I think some of our maps may need recompiling since we're in the middle of BSP format changes, but some might work..

**Comment by jdolan** [comment]
The main download link is working again, too. Feel free to join Discord if you want help setting up a `development` snapshot, as the `master` builds are about a year out of date now.
