### ISSUE TITLE
New game mode: Freezetag

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#9]
Classic freezetag mode

I liked Q3's implementation of the encasing ice when frozen, but would like it if the ice either melted or exploded without gibbing.

Static settings:

stand next to friendly frozen player (X amount of units away) for 3 seconds to thaw, thawed player respawns immediately

Tie into weapon banning/allowing to be able to have a unlimited railgun-only 1-hit freeze for instafreeze mode

Include lithium grapple

**Comment by jdolan** [comment]
This would be a great candidate for proving out our mod (separate game.dll) architecture.

**Comment by kaadmy** [comment]
I tried adding this a couple months ago, it got really difficult trying to get a half-dead state since everything independently hardcodes how dead acts.

**Comment by jdolan** [comment]
Why would players need to be half-dead? You could probably capture "frozen" state in the client's `stats` array -- that way it goes to the cgame automatically, too. And then, in terms of implementing freeze tag gameplay rules, you just force `PM_FREEZE` on the client, and add a blue shell effect to `ent->s.effects`.

But the point I was making, is that rather than clutter up the existing game module with more `g_gameplay` spaghetti, we could implement this as an actual mod.

I'd almost make the case that CTF, duel, TDM, arena, instagib.. could all be broken into separate, in some cases smaller, mods someday.

**Comment by jdolan** [comment]
(And, of course, the counter argument to that is: by going with our existing "mixins" approach to gameplay rules, you could combine freezetag with CTF or something)..
